# Generated by Django 4.1.4 on 2022-12-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Назва принтера')),
                ('api_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ доступу до API')),
                ('check_type', models.CharField(choices=[(0, 'kitchen'), (1, 'client')], default='client', max_length=128, verbose_name='Тип чеку')),
                ('point_id', models.IntegerField(verbose_name='Номер точки')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(0, 'kitchen'), (1, 'client')], default='client', max_length=128, verbose_name='Тип чеку')),
                ('order', models.JSONField(verbose_name='Інформація про замовлення')),
                ('status', models.CharField(choices=[(0, 'new'), (1, 'rendered'), (2, 'printed')], default='new', max_length=128, verbose_name='Статус чеку')),
                ('pdf_file', models.FileField(upload_to='', verbose_name='Посилання на PDF')),
                ('printer_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='printing_checks.printer', verbose_name='ID принтера')),
            ],
        ),
    ]
