# Generated by Django 4.1.4 on 2022-12-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=128, verbose_name='Статус чеку'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], default='client', max_length=128, verbose_name='Тип чеку'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], default='client', max_length=128, verbose_name='Тип чеку'),
        ),
    ]
